apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deploy
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    # After the next update, Deployment will kill one pod as a first step and then creates new version of the pod to keep total replicas count equal to amount set in spec. After the new pod becomes ready, the process will repeat with the next pod.
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    spec:
      securityContext:
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: metricity-quilt
          image: {{ .Values.metricity.image }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-config
            - secretRef:
                # env name should be TOKEN
                name: metricity-quilt-discord-token
          volumeMounts:
            - name: {{ .Chart.Name }}-metricity-storage
              mountPath: /metricity/config.toml
              subPath: config.toml
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
        - name: metabase-quilt
          image: {{ .Values.metabase.image }}
          securityContext:
            allowPrivilegeEscalation: false
            # capabilities:
            #   drop:
            #     - ALL
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-config
          ports:
            - containerPort: {{ .Values.metabase.port }}
              name: http
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ .Chart.Name }}-storage
          emptyDir: { }
        - name: {{ .Chart.Name }}-metricity-storage
          configMap: 
            name: {{ .Chart.Name }}-metricity-config
            items:
              - key: config.toml
                path: config.toml
