image: ghcr.io/quiltmc/cozy-discord:latest
namespace: quilt
replicaCount: 1

messageLogs: '839495849116958780,839496251463958548'
releaseChannels: '832351145073573889,832351173640978472'
statusChannel: '1009020306280681532'

# cf. https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
resources:
  limits:
    cpu: 400m
    memory: 924Mi
  requests:
    cpu: 400m
    memory: 724Mi

mongodb:
  auth:
    rootPassword: cozy
    usernames:
      - cozy
    passwords:
      - cozy
    databases:
      - cozy

s3-backups:
  database:
    password: cozy
