image:
  repository: 'ghcr.io/quiltmc/cozy-discord'
  tag: '956d2e7b7d128f9f1d7d086305bbca7435648d47'
namespace: quilt
replicaCount: 1
messageLogs: '839495849116958780,839496251463958548'
releaseChannels: '832351145073573889,832351173640978472'
statusChannel: '1009020306280681532'
# cf. https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
resources:
  limits:
    cpu: 400m
    memory: 1200Mi
  requests:
    cpu: 400m
    memory: 724Mi
mongodb:
  auth:
    rootPassword: cozy
    usernames:
      - cozy
    passwords:
      - cozy
    databases:
      - cozy
mongodb-s3-backup:
  database:
    password: cozy
