# Spec: https://helm.sh/docs/topics/charts/#the-chartyaml-file
apiVersion: v2
name: s3-backups
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.2
# This is the version number of the application being deployed (purely informational).
appVersion: '1'
description: helm chart handling Quilt's backups to an S3
home: https://github.com/QuiltMC/quilt-helm-charts
# A chart can be either an 'application' or a 'library' chart.
type: application
maintainers:
  - name: Pyrofab
    email: pyrofab@quiltmc.org
  - name: tibs
    email: tibs@quiltmc.org
dependencies:
  - name: mongodb
    version: 13.16.2
    repository: https://charts.bitnami.com/bitnami
